# kind: Service
# apiVersion: v1
# metadata:
#   name: myapp
#   labels:
#     env: dev
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-svc
  labels: 
    env: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    env: dev

