apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-30T14:00:36Z"
  generation: 1
  labels:
    run: nginx-pod
  name: nginx-new
  namespace: default
  resourceVersion: "17036"
  uid: 509e1933-7921-42cc-8d48-6ce21ffcfc94
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-g9gjk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cka-cluster2-worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-g9gjk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-12-30T14:01:02Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-12-30T14:00:36Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-12-30T14:01:02Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-12-30T14:01:02Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-12-30T14:00:36Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e182ccb9743f9d66f7284d34128beb1fb29db680eea3728616078f788e1dfee9
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:c8dc101ba61a499398c245fed8123abc20a3867ebd3664087890a054a781770b
    lastState: {}
    name: nginx-pod
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-12-30T14:01:02Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-g9gjk
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.6
  hostIPs:
  - ip: 172.18.0.6
  observedGeneration: 1
  phase: Running
  podIP: 10.244.4.3
  podIPs:
  - ip: 10.244.4.3
  qosClass: BestEffort
  startTime: "2025-12-30T14:00:36Z"
