apiVersion:  apps/v1
kind:  Deployment
metadata:
  name: myapp
  labels:
    env: dev
spec:
  template:
    metadata:
      name: nginx
      labels: 
        env: dev
    spec:
      containers:
        - name: myapp
          image: nginx:1.23.4-alpine
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels: 
      env: dev
