apiVersion:  v1
kind:  ReplicationController
metadata:
  name: nginx-rc
  labels:
    env: dev
spec:
  template:
    metadata:
      name: nginx
      labels: 
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
