apiVersion: v1
kind:  ReplicationController
metadata: 
  name: nginx-rc
  labels:
    env: dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        env: dev
      name: nginx-rc
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

